### ISSUE TITLE
Problem installing cURL on Windows

### ISSUE THREAD

**Issue by s2t2** [SCSU-CSC-Department/201701-csc-443-01#13]
Last class, one student was having an issue installing cURL on Windows given the existing link in the *windows-command-prompt.md* exercise.

To remedy, the existing instructions should be expanded or clarified.

**Comment by s2t2** [comment]
Maybe the wizard would be helpful: https://curl.haxx.se/dlwiz/

Or maybe the source code would work: https://github.com/curl/curl

I plan to test these approaches on a windows machine at my next available opportunity.

**Comment by 500ghz** [comment]
Once the zip has been downloaded the user needs to extract it and then enter the directory by "cd"ing into it and then just type "curl command" or "curl --help"

More information: http://stackoverflow.com/questions/9507353/how-do-i-install-set-up-and-use-curl-on-a-windows

**Comment by s2t2** [comment]
Thanks @500ghz
